title: 她已非昔日之她
email: linq.sophie@gmail.com
description: (＃ ﾟДﾟ)
baseurl: "" # the subpath of your site, e.g. /blog
url: http://underwaternya.github.io # the base hostname & protocol for your site, e.g. http://example.com
lang: zh-Hans
color_scheme: github
twitter_username: underwaternya
github_username:  underwaternya
disqus_shortname: underwaternya
google_analytics: UA-79254401-1

# RSS feed
name: 她已非昔日之她
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1

# Build settings
markdown: kramdown
remote_theme: jekyll-theme-kagami
exclude:
  - Gemfile
  - Gemfile.lock
