title:            她已非昔日之她
description:      唔。
url:              
signoff:          Qin LIN
disqus_shortname: underwaternya
google_analytics: UA-79254401-1
links:
  - name:         关于
    url:          /about
  - name:         其他
    url:          /others
highlighter:      rouge
permalink:        pretty
markdown:         kramdown
redcarpet:
  extensions:
    - smart
