title:            她已非昔日之她
description:      唔。
url:              
signoff:          Qin LIN
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         关于
    url:          /about
  - name:         其他
    url:          /others
highlighter:      rouge
permalink:        pretty
markdown:         kramdown
redcarpet:
  extensions:
    - smart
